version: '3'
volumes:
  postgres-data:
services:
  # db:
  #   image: keinos/sqlite3
    # restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_SERVE_STATIC_FILES=true
    # volumes:
    #   - .:/project # Only mount this volume if running Rails in development mode.
    ports:
      - "3000:3000"
    # depends_on:
      # - db
    # restart: always